##################################################
# my app
##################################################
---
- name: install my app
  hosts: all
  become: true
  pre_tasks:
  - name: "Disable se"
    lineinfile:
      path: "/etc/selinux/config"
      regexp: "^SELINUX="
      line: "SELINUX=disabled"

  - name: "reboot after se"
    reboot:

  roles:
    - postgres
    - geerlingguy.nginx  
    - nginx_conf
    - geerlingguy.ruby
    - myapp
