- name: "replace default config"
  ansible.builtin.template:
    src: files/default.rocky.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: vagrant
    group: vagrant
    mode: 0644

  notify:
    - "reload nginx"